packages:
    - .

onlyBuiltDependencies:
    - "@prisma/client"
    - "@prisma/engines"
    - "@tailwindcss/oxide"
    - core-js-pure
    - esbuild
    - prisma
    - sharp
    - unrs-resolver
    - workerd
